apiVersion: v1
kind: Service
metadata:
  name: backend-jose-gallardo-service
  namespace: jose-gallardo-namespace
spec:
  type: NodePort
  ports:
  - port: 30001
    targetPort: 8085
    nodePort: 30001
  selector:
    app: backend-jose-gallardo-deployment