apiVersion: v1
kind: Service
metadata:
  name: frontend-jose-gallardo-service
  namespace: jose-gallardo-namespace
spec:
  type: NodePort
  ports:
  - port: 30002
    targetPort: 4200
    nodePort: 30002
  selector:
    app: frontend-jose-gallardo-deployment
